### ISSUE TITLE
fails to resolve modules?

### ISSUE THREAD

**Issue by ghost** [astahmer/panda-monorepo#3]
Im sure this must be pilot error, so i apologise, but with no changes to the repo at all (same error both downloading the zip and using the template) i get multiple errors for all the included workspaces like this. What gormless beginner mistake am i making?

```
The plugin "vite:dep-scan" was triggered by this import

    src/App.tsx:4:29:
      4 │ import { ShadcnButton } from '@my-monorepo/button'
        ╵                              ~~~~~~~~~~~~~~~~~~~~~


✘ [ERROR] Failed to resolve entry for package "@my-monorepo/some-component". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-scan]
```

sorry. many. thanks for being patient with me!

**Comment by astahmer** [comment]
can't reproduce locally, did you build the button package ?
edit: if that still happens after building the button package, please describe the reproductions steps

**Comment by vrimar** [comment]
I'm facing a similar issue on Windows 10.

Node version: **20.9.0**
pnpm version: **8.10.2**

Steps to reproduce:

1. `git pull https://github.com/astahmer/panda-monorepo.git`
2. `cd panda-monorepo`
3. `pnpm i`
4. `pnpm --filter @my-monorepo/preset build`
5. `pnpm --filter @my-monorepo/button build`

Error:
```
PS C:\panda-monorepo> pnpm --filter @my-monorepo/button build

> @my-monorepo/button@1.0.0 build C:\panda-monorepo\packages\button
> tsup src/index.ts src/preset.ts --dts --format=esm,cjs --clean --dts --external @pandacss/dev --external @my-monorepo/ui-lib

CLI Building entry: src/index.ts, src/preset.ts
CLI Using tsconfig: tsconfig.json
CLI tsup v7.0.0
CLI Target: es2020
CLI Cleaning output folder
ESM Build start
CJS Build start
CJS dist\index.js  1.75 KB
CJS dist\preset.js 3.17 KB
CJS ⚡️ Build success in 45ms
ESM dist\preset.mjs 2.13 KB
ESM dist\index.mjs  653.00 B
DTS Build start
src/button.tsx(1,20): error TS2307: Cannot find module '@my-monorepo/ui-lib/css' or its corresponding type declarations.
src/button.tsx(2,56): error TS2307: Cannot find module '@my-monorepo/ui-lib/recipes' or its corresponding type declarations.
src/button.tsx(3,46): error TS2307: Cannot find module '@my-monorepo/ui-lib/jsx' or its corresponding type declarations.
src/button.tsx(9,6): error TS2339: Property 'className' does not exist on type 'ShadcnButtonProps'.
src/button.tsx(9,17): error TS2339: Property 'variant' does not exist on type 'ShadcnButtonProps'.
src/button.tsx(9,26): error TS2339: Property 'size' does not exist on type 'ShadcnButtonProps'.

Error: error occured in dts build
    at Worker.<anonymous> (C:\panda-monorepo\node_modules\.pnpm\tsup@7.0.0_typescript@5.0.2\node_modules\tsup\dist\index.js:2297:26)  
    at Worker.emit (node:events:514:28)
    at MessagePort.<anonymous> (node:internal/worker:263:53)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:807:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
DTS Build error
RollupError: Failed to compile. Check the logs above.
    at error (C:\panda-monorepo\node_modules\.pnpm\rollup@3.25.1\node_modules\rollup\dist\shared\rollup.js:317:30)
    at Object.error (C:\panda-monorepo\node_modules\.pnpm\rollup@3.25.1\node_modules\rollup\dist\shared\rollup.js:1668:20)
    at Object.error (C:\panda-monorepo\node_modules\.pnpm\rollup@3.25.1\node_modules\rollup\dist\shared\rollup.js:24985:42)
    at generateDtsFromTs (C:\panda-monorepo\node_modules\.pnpm\tsup@7.0.0_typescript@5.0.2\node_modules\tsup\dist\rollup.js:7498:22)  
    at C:\panda-monorepo\node_modules\.pnpm\tsup@7.0.0_typescript@5.0.2\node_modules\tsup\dist\rollup.js:7505:59
    at _nullishCoalesce (C:\panda-monorepo\node_modules\.pnpm\tsup@7.0.0_typescript@5.0.2\node_modules\tsup\dist\rollup.js:1:198)     
    at Object.transform (C:\panda-monorepo\node_modules\.pnpm\tsup@7.0.0_typescript@5.0.2\node_modules\tsup\dist\rollup.js:7505:18)   
    at C:\panda-monorepo\node_modules\.pnpm\rollup@3.25.1\node_modules\rollup\dist\shared\rollup.js:1861:40
C:\panda-monorepo\packages\button:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @my-monorepo/button@1.0.0 build: `tsup src/index.ts src/preset.ts --dts --format=esm,cjs --clean --dts --external @pandacss/dev --external @my-monorepo/ui-lib`al @my-monorepo/ui-lib`
Exit status 1
```
